input RegisterInput {
  username: String!
  email: String!
  password: String!
  bio: String
}
input LoginInput {
  email: String!
  password: String!
}
type User {
  id: ID!
  username: String!
  email: String!
  bio: String
  posts: [Post]
  postsCount: Int!
  createdAt: String!
  subscribers: [User]
}
extend type Query {
  findUserById(userId: ID!): User
  findAllUsers: [User]
  getMe: User
}
extend type Mutation {
  updateBio(userId: ID!, bio: String!): User
  subscribe(userId: ID!): User
  register(registerInput: RegisterInput!): User!
  login(loginInput: LoginInput!): User!
  logout: String
}