type Tag {
  id: ID!
  content: String!
  createdAt: String!
}
extend type Query {
  findTagById(tagId: ID!): Tag
  findTagsByContent(content: String!): [Tag]
  findAllTags: [Tag]
}
extend type Mutation {
  createTag(content: String!): Tag!
}
