input PostInput {
  title: String!
  body: String!
  image: String!
  tags: String!
}
type Post {
  id: ID!
  author: User!
  title: String!
  body: String!
  image: String
  likes: [User]!
  likeCount: Int!
  comments: [Comment]!
  commentCount: Int!
  tags: [Tag]!
  createdAt: String!
}
type Comment {
  id: ID!
  author: User!
  body: String!
  createdAt: String!
}
type PostQuery {
  posts: [Post]
  hasMore: Boolean
  last: String
}
extend type Query {
  findPostById(postId: ID!): Post
  findAllPosts(cursor: ID): PostQuery
  findPostsByTerm(term: String!, cursor: ID): PostQuery
  findPostsByTag(tag: String!, cursor: ID): PostQuery
}
extend type Mutation {
  createPost(postInput: PostInput!): Post!
  editPost(postId: ID!, postInput: PostInput!): Post!
  deletePost(postId: ID!): String
  createComment(postId: ID!, body: String!): Post!
  likePost(postId: ID!): Post!
}
